name: preview-deploy

on:
  workflow_run:
    workflows: [test-be-integration]
    types: [completed]
    branches-ignore: [main]

jobs:
  preview-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Vercel Preview Deploy ğŸš€
        uses: ./.github/workflows/actions/vercel-deploy
        with:
          environment: 'preview'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
