name: production-deploy

# on:
#   workflow_run:
#     workflows: [test-be-integration]
#     types: [completed]
#     branches: [main]

on:
  push:
    branches:
      - main

jobs:
  production-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Vercel Production Deploy ğŸš€
        uses: ./.github/workflows/actions/vercel-deploy
        with:
          environment: 'production'

      # - name: Install Vercel CLI ğŸ”§
      #   run: npm install --global vercel@latest

      # - name: Pull Vercel Environment Information â¬‡ï¸
      #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Build Project Artifacts ğŸ—ï¸
      #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Deploy Project Artifacts to Vercel ğŸš€
      #   run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
